package com.example.projectlibary.common;

public enum NotificationType {
    RESERVATION_AVAILABLE,
    DUE_DATE_REMINDER,
    OVERDUE_NOTICE,
    NEW_BOOK,
    EVENT,
    GENERAL,
    BORROW_EXPIRED,
    RETURN_CONFIRMED,
    FINE_ISSUED,
    RETURN_INITIATED_SAME_DAY_REMINDER,
    RETURN_CONFIRMATION_EXPIRED,
    RETURN_LIBRARIAN_CONFIRMED_OK,
    RETURN_LIBRARIAN_CONFIRMED_DAMAGED
}
